### ISSUE TITLE
Memory for Exposed Functions is Not Released

### ISSUE THREAD

**Issue by jeremyjh** [myfreeweb/hs-duktape#4]
When GHC creates a function pointer for Foreign Code, it allocates memory for it, but cannot determine when to free this. `freeHaskellFunctionPtr` must be called to release this memory.

This wouldn't matter for applications that only use a single context that lives as long as the application, but the application I'm developing will be instantiating many, many contexts over the course of its lifetime, and some of those functions will be closures.

I quickly played with a very basic [implementation](https://github.com/jeremyjh/hs-duktape/commit/3b89757de170006967805a573faef4cae8e3db6c) that simply returns release actions from `exposeFnDuktape` and tells the programmer to call them. Ha!

I don't think that's actually the right approach. Instead I think probably the structure in `DuktapeCtx` should store a release action that `exposeFnDuktape` will append to with `freeHaskellFunctionPtr`, and then we use a finalizer to run that when the pointer is released. We'd maybe need to use the `Foreign.Concurrent` version of of `newForeignPtr` so that we can use a `addForeignPtrFinalizer` that calls IO actions.

If this sounds ok I'm happy to submit a PR.

**Comment by myfreeweb** [comment]
Nice catch. I think even the manual cleanup ("telling the programmer") is fine :)
