### ISSUE TITLE
Support for DUK_USE_EXEC_TIMEOUT_CHECK ?

### ISSUE THREAD

**Issue by jeremyjh** [myfreeweb/hs-duktape#6]
My app needs Duktape to be a secure sandbox for running untrusted code. Some things - like using custom allocators to limit heap space - I can handle outside this library by calling `createHeap` myself to create the context.

Handling timeouts is tricky though, and I need to do that to defeat `while(true) {}`. It looks like the way this has to work is that a function callback must be defined in `DUK_USE_EXEC_TIMEOUT_CHECK`  at compile time of the library. It calls a function with the user data that was passed to duk_create_heap, that tells it whether to timeout or not.

Ideally `hs-duktape` would provide a way for the application to register its own callback for a timeout check, otherwise it just uses a default that always passes the check. The compile time function exposure really limits our options though. I think `hs-duktape` would need to include its own header that defines `DUK_USE_EXEC_TIMEOUT_CHECK` and the function prototype it will call, and then includes `duktape.h`. The function that `hs-duktape` defines would read a global ref to get the function to actually do the evaluation, which by default would just pass the check. That global ref then just needs to be exposed to a setter function for the application to call.

Is this something you think `hs-duktape` should support, and would a PR along these lines be welcome?

**Comment by myfreeweb** [comment]
Of course, pretty much any PR would be welcome :)
