### ISSUE TITLE
Release with new features?

### ISSUE THREAD

**Issue by taphu** [myfreeweb/hs-duktape#9]
Is there a plan to release a new version to hackage with the recent updates? I feel as though some of them are quite valuable (https://github.com/myfreeweb/hs-duktape/issues/6 in particular is what I came here looking for :smiley: ).

Thanks.

**Comment by jeremyjh** [comment]
bump @myfreeweb

**Comment by myfreeweb** [comment]
done

**Comment by taphu** [comment]
Thanks!
